  var syllabus = {
    active:{
      url:"https://educatorinnovator.org/wp-content/uploads/2020/04/Let%E2%80%99s-Give-Them-Something-to-Talk-And-Act-About-Privilege-Racism-and-Oppression-in-the-Middle-School-Classroom.pdf",
      summary:""
    },
    november:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EE0512Jan19Whiteness.pdf",
      summary:""
    },
    december:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EJ1084Mar19Miles.pdf",
      summary:""
    },
    january:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2020/01/VM0272Dec19Revising.pdf",
      summary:""
    },
    february:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/RTE0534May19Praisesongs.pdf",
      summary:""
    },
    march:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/RTE0531aug18Untold.pdf",
      summary:""
    },
    april:{
      url:"https://educatorinnovator.org/wp-content/uploads/2020/04/Let%E2%80%99s-Give-Them-Something-to-Talk-And-Act-About-Privilege-Racism-and-Oppression-in-the-Middle-School-Classroom.pdf",
      summary:""
    },
    may:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EE0514Jul19Performative.pdf",
      summary:""
    }
  }