  var syllabus = {
    active:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EJ1084Mar19Miles.pdf",
      summary:""
    },
    november:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EE0512Jan19Whiteness.pdf",
      summary:""
    },
    december:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EJ1084Mar19Miles.pdf",
      summary:""
    },
    february:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/RTE0534May19Praisesongs.pdf",
      summary:""
    },
    april:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/RTE0531aug18Untold.pdf",
      summary:""
    },
    may:{
      url:"https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EE0514Jul19Performative.pdf",
      summary:""
    }
  }